name: Release
on:
  #push:
  #  branches:
  #    - "main"
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build linux/${{ matrix.platform }}
        run: make images -j $(nproc)

      - name: Login to quay.io
        run: docker login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

      - name: Push linux/${{ matrix.platform }}
        run: make push -j $(nprox)
