name: Release
on:
  #push:
  #  branches:
  #    - "main"
  workflow_dispatch: { }
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io  # Use robot account!
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build linux/${{ matrix.platform }}
        run: make images -j$(($(nproc)/2)) # each image will already build amd64 and (emulated) arm64 in parallel anyway

      - name: Push linux/${{ matrix.platform }}
        run: make push -j $(nprox)
